baseURL = 'https://vpuri3.github.io/'
languageCode = 'en-us'
title = 'Vedant Puri'
theme = 'PaperMod'

[params]
defaultTheme = 'dark'
disableSpecial1stPost = true
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = false
images = ['https://github.com/vpuri3.png']

[params.assets]
favicon = 'https://github.githubassets.com/favicons/favicon.png'
favicon16x16 = 'https://github.githubassets.com/favicons/favicon.png'
favicon32x32 = 'https://github.githubassets.com/favicons/favicon.png'
apple_touch_icon = 'https://github.com/vpuri3.png'
safari_pinned_tab = 'https://github.githubassets.com/favicons/favicon.svg'

[markup.goldmark.renderer]
unsafe = true

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/vpuri3'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/vpuri3/'

[[params.socialIcons]]
name = 'email'
url = 'mailto:vedantpuri@cmu.edu'

[[menu.main]]
identifier = 'featured'
name = 'Featured'
url = '/#featured-work'
weight = 10

[[menu.main]]
identifier = 'research'
name = 'Research'
url = '/#research-themes'
weight = 20

[[menu.main]]
identifier = 'open-source'
name = 'Open Source'
url = '/#open-source'
weight = 30

[[menu.main]]
identifier = 'work'
name = 'Work'
url = '/work/'
weight = 40

[[menu.main]]
identifier = 'blog'
name = 'Blog'
url = '/blog/'
weight = 55

[[menu.main]]
identifier = 'photography'
name = 'Photography'
url = '/photography/'
weight = 60

[outputs]
home = ['HTML', 'RSS', 'JSON']
